#!/bin/bash
echo "Deploying jobstartinc/sixpack:$CIRCLE_SHA1"
docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
docker tag -f jobstartinc/sixpack:$CIRCLE_SHA1 jobstartinc/sixpack:latest
docker push jobstartinc/sixpack:$CIRCLE_SHA1
docker push jobstartinc/sixpack:latest
